#!/bin/bash
echo "** Started creating default DB and users"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_PASSWORD" <<-EOSQL
  -- Create extensions
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

  -- Create test schema
  CREATE SCHEMA IF NOT EXISTS test;

  CREATE USER $POSTGRES_APP_USER WITH PASSWORD '$POSTGRES_APP_PASSWORD';
  CREATE USER $POSTGRES_TEST_USER WITH PASSWORD '$POSTGRES_TEST_PASSWORD';

  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT INSERT, SELECT, UPDATE ON TABLES TO "$POSTGRES_APP_USER";
  GRANT ALL ON SCHEMA test TO "${POSTGRES_TEST_USER}";

  ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_TEST_USER" IN SCHEMA test
  GRANT SELECT, INSERT, UPDATE ON TABLES TO "$POSTGRES_APP_USER";

  GRANT $POSTGRES_TEST_USER TO $POSTGRES_APP_USER;
  SET search_path TO public, test;
EOSQL

echo "** Finished creating default DB and users"